Proj1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from clothes.views import home_views, material_silk_views, material_cotton_views, about_views



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_views ),
    path('Silk/', material_silk_views),
    path('Cotton/', material_cotton_views),
    path('about/', about_views),
    

    ]
urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proj1/clothes/models.py
from django.db import models

class Products(models.Model):

    Material_Choice=[('S','Silk'),
    ('C','Cotton')]

    Clothe_Choice=[('SA','Saree'),
    ('KU','Kurta'),
    ('DU','Dupatha'),]
    Category_Choice=[('CKS', 'Chanderi Kataan Silk'),
('CSK','Chanderi Silk Cotton'),
('CSS','Chanderi Soft Silk'),
('KaSC','Kanchipuram Silk Cotton'),
('KuSC','Kuppadam Silk Cotton'),
('LC','Linen Cotton'),
('SL','Silk Linen')]

    Vendor_Choice=[('KS','KS'),
    ('RM','RM'),
    ('AP','AP'),]

    Title       = models.CharField(max_length=200)
    Description = models.TextField()
    Material    = models.CharField(max_length = 100, choices = Material_Choice, default = 'C')
    Clothe_Type = models.CharField(max_length = 100, choices = Clothe_Choice, default = 'SA')
    Category    = models.CharField(max_length = 100, choices = Category_Choice, default = 'CKS')
    Vendor      = models.CharField(max_length = 100, choices = Vendor_Choice, default = 'KS')
    Price       = models.DecimalField(max_digits = 100 ,decimal_places = 2, default=0 )
    Offer       = models.BooleanField(default=False)
    Image       = models.ImageField(upload_to='pics')
    #ks, rm, ap
    

    

Proj1/clothes/views.py
from django.shortcuts import render
from .models import Products

# Create your views here.
def home_views(request):
    all_items = Products.objects.all()
    return render(request,'homepage.html',{'all_items':all_items})
    #return render(request,'base.html',{})

def material_silk_views(request):
    all_items = Products.objects.all()
    return render(request,'Materials_Silk.html',{'all_items':all_items})

def material_cotton_views(request):
    all_items = Products.objects.all()
    return render(request,'Materials_Cotton.html',{'all_items':all_items})

def about_views(request):
    return render(request,'about.html')


    

Proj1/templates/Materials_Cotton.html
{%extends 'base.html'%}
{%load static%}<!--

{% static 'images' as BaseURL%}-->
{%block content1%}
<div class="home">

	<!-- Home Slider -->
	<div class="home_slider_container" style="height: 200px;" >
		<div class="owl-carousel owl-theme home_slider" style="height: 200px;" >

			<!-- Slide -->
			<div class="owl-item" style="height: 200px;">
				<!---->
				<div class="background_image" style="background-image:url({% static 'images/Thread_background.jpg' %}); height: 200px;">
				</div>
				<div class="home_slider_content_container"style="height: 200px;">
					<div class="container " style="height: 200px;">
						<div class="row" style="height: 200px;">
							<div class="col" style="height: 200px;">
								<div class="home_slider_content" style="height: 200px;">
									
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{%endblock%}
{%block content2%}
    <div class="destinations" id="destinations">
		<div class="container">
			<div class="row">
				<div class="col text-center">
					<div class="section_title"><h2>Cotton</h2></div>
					<div class="section_subtitle">
						Comfortable and Stylish At The Same Time
					<div>
						
				</div>
			</div>
			<div class="row destinations_row">
				<div class="col">
					<div class="destinations_container item_grid">

						<!-- Destination -->
						{%for item in all_items%}
						<div class="destination item">
                            {%if item.get_Material_display == 'Cotton' %}
							<div class="destination_image">
                               
								<!-- IF A STATIC URL DO LIKE BELOW
                                <img src="{{BaseURL}}/{{dest.img}}" alt="">-->
                                
								<img src={{item.Image.url}} alt="">
								{%if item.Offer%}
								<div class="spec_offer text-center"><a href="#">Special Offer</a></div>
								{%endif%}
								
							</div>
							<div class="destination_content">
								<div class="destination_title"><a href="destinations.html">{{item.Title}}</a></div>
                                <div class="destination_subtitle"><p>{{ item.Description }}</p></div>
                                <div class="destination_subtitle"><p>{{ item.get_Clothe_Type_display  }}</p></div>
								<div class="destination_subtitle"><p>{{ item.get_Material_display  }}</p></div>
                                <div class="destination_price">{% if item.Price == 0.0 %}
									Contact For Price
									{%else%}
									From ₹{{item.Price}}
									{%endif%}</div>
                                
                            </div>
                            {% endif %}
						</div>
						{%endfor%}
						{% endblock %}

Proj1/templates/Materials_Silk.html
{%extends 'base.html'%}
<!--
{%load static%}
{% static 'images' as BaseURL%}-->
{%block content1%}
<div class="home">

	<!-- Home Slider -->
	<div class="home_slider_container" style="height: 200px;" >
		<div class="owl-carousel owl-theme home_slider" style="height: 200px;" >

			<!-- Slide -->
			<div class="owl-item" style="height: 200px;">
				<!---->
				<div class="background_image" style="background-image:url({% static 'images/Thread_background.jpg' %}); height: 200px;">
				</div>
				<div class="home_slider_content_container"style="height: 200px;">
					<div class="container " style="height: 200px;">
						<div class="row" style="height: 200px;">
							<div class="col" style="height: 200px;">
								<div class="home_slider_content" style="height: 200px;">
									
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{%endblock%}

{%block content2%}
    <div class="destinations" id="destinations" style="padding: 15px;">
		<div class="container" >
			<div class="row" style="height: fit-content;">
				<div class="col text-center">
					<div class="section_title"><h2>Silk</h2></div>
					<div class="section_subtitle">
						Strong. breathable. Elegant.  You cannot go wrong with Silk
					<div>
						
				</div>
			</div>
			<div class="row destinations_row">
				<div class="col">
					<div class="destinations_container item_grid">

						<!-- Destination -->
						{%for item in all_items%}
						<div class="destination item">
                            {%if item.get_Material_display == 'Silk' %}
							<div class="destination_image">
                               
								<!-- IF A STATIC URL DO LIKE BELOW
                                <img src="{{BaseURL}}/{{dest.img}}" alt="">-->
                                
								<img src={{item.Image.url}} alt="">
								{%if item.Offer%}
								<div class="spec_offer text-center"><a href="#">Special Offer</a></div>
								{%endif%}
								
							</div>
							<div class="destination_content">
								<div class="destination_title"><a href="destinations.html">{{item.Title}}</a></div>
                                <div class="destination_subtitle"><p>{{ item.Description }}</p></div>
                                <div class="destination_subtitle"><p>{{ item.get_Clothe_Type_display  }}</p></div>
								<div class="destination_subtitle"><p>{{ item.get_Material_display  }}</p></div>
                                <div class="destination_price">
									{% if item.Price == 0.0 %}
									Contact For Price
									{%else%}
									From ₹{{item.Price}}
									{%endif%}</div>
                                
                            </div>
                            {% endif %}
						</div>
						{%endfor%}
						{% endblock %}

Proj1/templates/about.html
{% extends 'base.html' %}
{% load static %}
{%block content1%}
<link href='https://fonts.googleapis.com/css?family=B612' rel='stylesheet'>
<div class="home">

    <!-- Home Slider -->
    <div class="home_slider_container" style="height: 200px;">
        <div class="owl-carousel owl-theme home_slider" style="height: 200px;">

            <!-- Slide -->
            <div class="owl-item" style="height: 200px;">
                <!---->
                <div class="background_image"
                    style="background-image:url({% static 'images/Thread_background.jpg' %}); height: 200px;">
                </div>
                <div class="home_slider_content_container" style="height: 200px;">
                    <div class="container " style="height: 200px;">
                        <div class="row" style="height: 200px;">
                            <div class="col" style="height: 200px;">
                                <div class="home_slider_content" style="height: 200px;">

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {%endblock%}
            {%block content2%}
            <html>

            <body >
                <H1 style="font-size: 100px; padding-left:50px ; padding-top: 100px;font-family: Oswald; color: goldenrod; font-weight: bold; background-color:teal;"> Tantuvis </H1>
                <h2 style="font-family: Oswald; color: gold; padding-left: 67px; background-color: teal;"> For The Weavers</h2>
                <div class="about_body" >   
                    <div class="parallax_background parallax-window" data-parallax="scroll"
            data-image-src="{% static 'images/about_weaver.jpg' %}" data-speed="0.8"></div>      
            <div class="container">
                <div class="row">
                    <div class="col">
                        <div class="newsletter">
                            
                <p style="font-family: B612;"> 
                    Tantuvi means weavers in Sanskrit the 3500 year old language of ancient India. The works of Hindu philosophy and and
                    compositions were predominantly written in Sanskrit.
                    In Modern India ,the language is now only heard as a recital of prayer or songs in temples but not
                    spoken in India.
                    One can relate weaving as ancient art of India in same level as Sanskrit to ancient India.
                    Fortunately, it still exists and is still striving hard along with the modern textile industry.
<br>
<br>
                    Who we are and how are we going to help the Tantuvis?

                    We bring genuine handloom sarees from weavers to you. 
                    Our objective is to help the Tantuvis to showcase their products to the world.
                    'WE-AVE REVIVE... WE SURVIVE' is the voice of many weavers which we are getting it across to you.

<br>
<br>
                    It is time that we as global community take action to make this industry survive and encourage the
                    Tantuvis to not stop but weave more. Feel the weave and make them live.
                </div>

            </body>

            </html>
            {%endblock%}

Proj1/templates/homepage.html
{%extends 'base.html'%}
{%load static%}
{% static 'images' as BaseURL%}


{%block content1%}
<div class="home" >

	<!-- Home Slider -->
	<div class="home_slider_container">
		<div class="owl-carousel owl-theme home_slider">

			<!-- Slide -->
			<div class="owl-item">
				<!---->
				<div class="background_image" style="background-image:url({% static 'images/Thread_background.jpg' %})">
				</div>
				<div class="home_slider_content_container">
					<div class="container">
						<div class="row">
							<div class="col">
								<div class="home_slider_content">
									<div class="home_title">
										<h2>Designs To Live For </h2>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
			{%endblock%}
			{%block content2%}
			<div class="destinations" id="destinations" style="height: max-content;">
				<div class="container">
					<div class="row">
						<div class="col text-center">
							<div class="section_subtitle">Perfection of the craft</div>
							<div class="section_title">
								<h2>Popular Designs</h2>
							</div>
						</div>
					</div>
					<div class="row destinations_row">
						<div class="col">
							<div class="destinations_container item_grid">

								<!-- Destination -->
								{%for item in all_items%}
								<div class="destination item">
									<div class="destination_image">
										<!-- IF A STATIC URL DO LIKE BELOW
								<img src="{{BaseURL}}/{{dest.img}}" alt="">-->
										<img src={{item.Image.url}} alt="">
										{%if item.Offer%}
										<div class="spec_offer text-center"><a href="#">Special Offer</a></div>
										{%endif%}

									</div>
									<div class="destination_content">
										<div class="destination_title"><a href="destinations.html">{{item.Title}}</a>
										</div>
										<div class="destination_subtitle">
											<p style="color:#181818 ;">
												{{item.Description}}
												<hr color="#181818">
											</p>
											<p style="color:#181818 ;">
												{{item.get_Clothe_Type_display  }}
												<hr color="#181818">
											</p>
											<p style="color:#181818 ;">	
												{{ item.get_Category_display }}
											</p>
										</div>

										<div class="destination_price">
											{% if item.Price == 0.0 %}
											Contact For Price
											{%else%}
											From ₹{{item.Price}}
											{%endif%}
											</div>
									</div>
								</div>
								{%endfor%}
								{%endblock%}